version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: vle-postgres
    restart: always
    environment:
      POSTGRES_USER: vle-admin
      POSTGRES_PASSWORD: vle-admin-password
      POSTGRES_DB: vle
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mongodb:
    image: mongo:6
    container_name: vle-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: vle-mongo-admin
      MONGO_INITDB_ROOT_PASSWORD: vle-mongo-password
      MONGO_INITDB_DATABASE: vle
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:7
    container_name: vle-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    image: vleapi:latest
    container_name: vle-api
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vle
      SPRING_DATASOURCE_USERNAME: vle-admin
      SPRING_DATASOURCE_PASSWORD: vle-admin-password
      SPRING_DATA_MONGODB_URI: mongodb://vle-mongo-admin:vle-mongo-password@mongodb:27017/vle?authSource=admin
      JWT_SECRET: super-secret-key-vle-ultra-123456789012345678s901234
      CLOUD_S3_BUCKET: vle-service-upload
      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: AKIA2YWWLLT5KV43NK2N
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: dummy
      ADMIN_BOOTSTRAP_SECRET: bootstrap-super-duper-secret-knalis-key
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8060:8080"
    depends_on:
      - postgres
      - mongodb
      - redis

volumes:
  pgdata:
  mongodata:
