version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: vle-postgres
    restart: always
    environment:
      POSTGRES_USER: vle-admin
      POSTGRES_PASSWORD: vle-admin-password
      POSTGRES_DB: vle
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata: